language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vanillajs' ]; then cd .. && eval "mv $currentfolder generator-vanillajs" && cd generator-vanillajs; fi

